### ISSUE TITLE
Adobe Reader Crashes when accessing Custom Fields

### ISSUE THREAD

**Issue by KennyBu** [citizenparker/EotE-NPC-Sheet#1] opened 2015-08-26 19:28 UTC
When I try to make changes to the editable fields Adobe Reader crashes:

Adobe Reader 11.0.12

Faulting application name: AcroRd32.exe, version: 11.0.12.18, time stamp: 0x55913bd0
Faulting module name: AcroForm.api, version: 11.0.12.18, time stamp: 0x559139cb
Exception code: 0xc0000005
Fault offset: 0x000b0cae
Faulting process id: 0x4bf4
Faulting application start time: 0x01d0e03462fd45d6
Faulting application path: C:\Program Files (x86)\Adobe\Reader 11.0\Reader\AcroRd32.exe
Faulting module path: C:\Program Files (x86)\Adobe\Reader 11.0\Reader\plug_ins\AcroForm.api
Report Id: ac503774-4c27-11e5-8281-a02bb82f7848
Faulting package full name: 
Faulting package-relative application ID: 

![issue](https://cloud.githubusercontent.com/assets/511550/9503745/dc38c2bc-4c06-11e5-895c-46b7efa50560.png)

**Comment by sparkertime** [comment] 2015-08-26 19:34
Thanks for reaching out. I'm sorry you ran into this problem, but I'm glad
to know someone else is using these sheets!

I have run into this myself and I have yet to figure out the issue, but I
intend to keep trying. In the meantime, you can downgrade to Adobe Reader
11.0.10 which does not have this problem.

Download Links:

OSX: http://downloads.netmediaeurope.de/3026/adobe-reader-mac/
Windows:
http://www.adobe.com/support/downloads/thankyou.jsp?ftpID=5865&fileID=5893
(I think? I don't actually have a Windows machine handy to test this out)

**Comment by KennyBu** [comment] 2015-08-26 19:37
Scott, I actually love the sheets, thanks for creating them! As a GM for EotE they come in really handy! Let me know if you discover a solution. In the meantime I will try to downgrade on my Windows 7 machine. Thanks again....Ken

**Comment by sparkertime** [comment] 2015-08-27 01:38
@KennyBu Thanks for the kind words!

I updated the sheet stored here. The sheet is now editable in Adobe Reader OSX 11.0.12 and I _think_ it should be fixed in Windows as well. Older versions of the sheet will still have this issue, so I hope you didn't lose a ton of work. (If I get PDF exports working from http://swsheets.com then hopefully it will deprecate these PDFs entirely!)

If anyone else comes looking for this issue on the internet, here's the root cause: In versions of Adobe Reader prior to 11.0.12, calling `this.removeField` on a field that doesn't exist does nothing. In Adobe Reader 11.0.12, this causes Adobe Reader to crash. You can prevent this by only calling `this.removeField` method when `this.getField` returns a non-null value.

**Closed as completed by sparkertime** 2015-08-27 01:38 UTC
